### ISSUE TITLE
Add clean_up2 before the list for the GW

### ISSUE THREAD

**Issue by domg2019** [BlueLemon1992/shell#1]
for this part in the function ---- checkGW
function checkGw()
{
    for gw in $(grep GW ${configFile} | grep -v "^#")
    do
        server=$(echo ${gw} | cut -d\| -f1);
        remoteHostName=$(echo ${gw} | cut -d\| -f2);
        echo "${server}";
        case ${willCheckOldFile} in
            true)
                    /usr/bin/ssh -o StrictHostKeyChecking=no ${remoteHostName} '\
                    PATH=/ext/schenker/toolslocal:/opt/sfw/bin:$PATH;\
                    echo -en "Error:"; ls /ext/schenker/data/error | wc -l; ls /ext/schenker/data/error | cut -d\. -f1 | sort | uniq -c;\
                    echo "Old file checking:"; /ext/schenker/toolslocal/list2 -fileagemin=30;\
                    ' 2>/dev/null;
                    ;;
            false)
                    /usr/bin/ssh -o StrictHostKeyChecking=no ${remoteHostName} '\
                    PATH=/ext/schenker/toolslocal:/opt/sfw/bin:$PATH;\
                    echo -en "Error:"; ls /ext/schenker/data/error | wc -l; ls /ext/schenker/data/error | cut -d\. -f1 | sort | uniq -c;\
                    ' 2>/dev/null;
                    ;;
        esac
        checkAndBeep;
        cleanUpRemoteGw;
        printLine;
    done
}

Before listing all errors under the err directory, directly hk some ignoring files with clean_up2.

**Comment by domg2019** [comment]
how about add this or change the cleanUpRemoteGw with this:
{
   /usr/bin/ssh	-o StrictHostKeyChecking=no ${remoteHostName} '\
   PATH=/ext/schenker/toolslocal:/opt/sfw/bin:$PATH;\
   cd /ext/schenker/data/error;
   clean_up2 -v;
}

no judgement, directly do clean_up2 -v

**Comment by BlueLemon1992** [comment]
> how about add this or change the cleanUpRemoteGw with this:
> {
> /usr/bin/ssh	-o StrictHostKeyChecking=no ${remoteHostName} '
> PATH=/ext/schenker/toolslocal:/opt/sfw/bin:$PATH;
> cd /ext/schenker/data/error;
> clean_up2 -v;
> }
> 
> no judgement, directly do clean_up2 -v

**Comment by BlaueZitrone** [comment]
Hi  @domg2019 
Of course, we can execute clean_up2 before scan the error folder.
But it is all about choice, in the current implementation, I choose to let the user decide when to run clean_up2.
Different people have different thoughts, I think it's better to give the right to users to decide something which makes the script more flexible but more complex.
